### ISSUE TITLE
Users feature tracking issue

### ISSUE THREAD

**Issue by humbkr** [humbkr/albaplayer#20]
This issue tracks the progress of the "users" feature.

For the first iteration, users will only be a username (no authentication management) and will be used to store user data like preferences on the backend.

Issues by priority:
- [x] https://github.com/humbkr/albaplayer/issues/12
- [x] https://github.com/humbkr/albaplayer/issues/13
- [x] https://github.com/humbkr/albaplayer/issues/14
- [x] https://github.com/humbkr/albaplayer/issues/15
- [ ] https://github.com/humbkr/albaplayer/issues/19
- [ ] https://github.com/humbkr/albaplayer/issues/18
- [x] https://github.com/humbkr/albaplayer/issues/16
- [x] https://github.com/humbkr/albaplayer/issues/17
